name: ci

on:
  pull_request:
      types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          tags: drpsychick/githubtraffic:test
          push: false
          load: true
      - name: Test image
        uses: addnab/docker-run-action@v3
        with:
          image: drpsychick/githubtraffic:test
          run: "/bin/sh /github-influx.sh"
